### ISSUE TITLE
Uncaught TypeError: Proxmox.Utils.overrideNotificationFieldName is not a function on latest PBS Docker (works on v3.1)

### ISSUE THREAD

**Issue by m0eak** [ayufan/pve-backup-server-dockerfiles#70]
After updating from Proxmox Backup Server (PBS) Docker image v3.1 to the latest tag, the web management interface loads as a blank page. In the browser console, the following error appears:

Uncaught TypeError: Proxmox.Utils.overrideNotificationFieldName is not a function
    at constructor (proxmox-backup-gui.js:954:16)
    at new constructor (ext-all.js:22:102290)
    at Ext.Inventory.<anonymous> (ext-all.js:22:115218)
    at Ext.Inventory.processCreate (ext-all.js:22:112788)
    at constructor.<anonymous> (ext-all.js:22:112578)
    at a.onBeforeCreated (ext-all.js:22:102552)
    at a.doProcess (ext-all.js:22:103286)
    at a.process (ext-all.js:22:103114)
    at new a (ext-all.js:22:102436)
    at Ext.Inventory.create (ext-all.js:22:112198)

Environment

Docker image: latest

Previously working image: v3.1

Browser: Edge

Host OS: Unraid7.0.1
